name: 'Docker Build Action'
description: ''
inputs:
  username: 
    description: ''
    required: true
    default: null
  password: 
    description: ''
    required: true
    default: null
  platforms: 
    description: ''
    required: false
    default: linux/amd64
  tags: 
    description: ''
    required: true
    default: null

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: ${{ inputs.platforms }}
        tags: ${{ inputs.tags }}
